import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, ArrowUpDown, BusFront, ChartNoAxesColumnIncreasing, Check, ChevronRight, Clock3, ExternalLink, Info, ListFilter, LoaderCircle, Map, Star, Radio, RefreshCw, Route as RouteIcon, Search, Settings2, ShieldAlert, TriangleAlert, X } from 'lucide-react';
import { api } from './api';
import { FAVORITES_KEY, readFavorites, type FavoriteRoute } from './favorites';
import { Chart } from './Chart';
import { ScenarioView } from './ScenarioView';
import type { Risk, Route, Settings, Snapshot, Summary, Vehicle } from './types';
import { age, delay, downloadCsv, riskLabels, routeHref, time } from './utils';
const TransportMap = lazy(()=>import('./TransportMap'));
type View = 'network'|'routes'|'incidents'|'history'|'settings';
type ServiceFilter = 'all'|'night'|'day';
const readQuery = () => new URLSearchParams(window.location.search);
const icons={network:Map,routes:BusFront,incidents:TriangleAlert,history:Clock3,settings:Settings2};
const names:Record<View,string>={network:'Сеть',routes:'Маршруты',incidents:'Инциденты',history:'История',settings:'Настройки'};

function RiskBadge({risk}:{risk:Risk}) { return <span className={`risk-badge ${risk}`}><i/>{riskLabels[risk]} риск</span>; }
function Empty({children}:{children:React.ReactNode}) {return <div className="empty-state"><ListFilter size={25}/><strong>{children}</strong><span>Измените поиск или фильтр риска.</span></div>;}
function Metrics({summary,routeMode}:{summary:Summary;routeMode:boolean}) {
  const items=routeMode ? [
    {name:'ТС на линии',value:summary.activeVehicles,suffix:'в демо-сценарии',Icon:BusFront},
    {name:'Инциденты',value:summary.incidentCount,suffix:'требуют внимания',Icon:TriangleAlert,tone:'high'},
    {name:'Среднее отклонение',value:delay(summary.averageDelaySeconds),suffix:'от расписания',Icon:Clock3},
    {name:'Худшее отклонение',value:delay(summary.worstDelaySeconds),suffix:'прогноз задержки',Icon:ChartNoAxesColumnIncreasing,tone:'high'},
  ] : [
    {name:'ТС на линии',value:summary.activeVehicles,suffix:'в демо-сценарии',Icon:BusFront},
    {name:'Маршруты',value:summary.routeCount,suffix:'ночная сеть',Icon:RouteIcon},
    {name:'Высокий риск',value:summary.highRiskCount,suffix:'ТС',Icon:TriangleAlert,tone:'high'},
    {name:'Средний прогноз',value:delay(summary.averageDelaySeconds),suffix:'мин:сек',Icon:Clock3,tone:'medium'},
    {name:'Данные свежие',value:`${summary.freshPercent}%`,suffix:'по порогу связи',Icon:Radio},
  ];
  return <div className={`metrics ${routeMode?'four':''}`}>{items.map(({name,value,suffix,Icon,tone})=><div className={`metric ${tone||''}`} key={name}><span className="metric-icon"><Icon size={28} strokeWidth={1.7}/></span><div><span className="metric-label">{name}</span><div className="metric-value">{value}<small>{suffix}</small></div></div></div>)}</div>;
}

function SettingsView({settings,onSaved}:{settings:Settings;onSaved:()=>void}) {
  const [draft,setDraft]=useState(settings),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setError('');setSaved(false);setBusy(true);try{await api.saveSettings(draft);setSaved(true);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <form className="panel settings-form" onSubmit={submit}><h2>Пороги и цвета риска</h2><p>Единые правила для метрик, карты и инцидентов. Порог сравнивается с прогнозируемой задержкой в секундах.</p><div className="settings-fields"><label>Средний риск, от (сек)<input type="number" min={1} max={3599} value={draft.mediumDelaySeconds} required onChange={e=>{setDraft({...draft,mediumDelaySeconds:Number(e.target.value)});setSaved(false);}}/></label><label>Высокий риск, от (сек)<input type="number" min={draft.mediumDelaySeconds+1} max={3600} value={draft.highDelaySeconds} required onChange={e=>{setDraft({...draft,highDelaySeconds:Number(e.target.value)});setSaved(false);}}/></label><label>Данные устарели через (сек)<input type="number" min={15} max={3600} value={draft.staleAfterSeconds} required onChange={e=>{setDraft({...draft,staleAfterSeconds:Number(e.target.value)});setSaved(false);}}/></label></div><div className="color-fields">{(['low','medium','high'] as const).map(r=><label key={r}>{riskLabels[r]} риск<input type="color" value={draft.colors[r]} onChange={e=>{setDraft({...draft,colors:{...draft.colors,[r]:e.target.value}});setSaved(false);}}/></label>)}</div><p className="help-text">Настройки общие для вкладок и хранятся в памяти демо-сервера до его перезапуска. Цвет дублируется текстовой меткой.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="primary-button" disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>}Сохранить настройки</button>{saved&&<span className="good" role="status">Настройки сохранены</span>}</div></form>;
}

function Filters({view,search,riskFilter,navigate}:{view:View;search:string;riskFilter:Risk|'all';navigate:(values:Record<string,string|null>)=>void}){return <div className="filters"><label className="search-box"><Search size={16}/><input aria-label="Поиск маршрута или ТС" placeholder={view==='incidents'?'Маршрут, ТС или остановка…':'Поиск маршрута…'} value={search} onChange={e=>navigate({q:e.target.value||null})}/>{search&&<button aria-label="Очистить поиск" onClick={()=>navigate({q:null})}><X size={14}/></button>}</label><label className="select-icon"><ListFilter size={15}/><select aria-label="Фильтр риска" value={riskFilter} onChange={e=>navigate({risk:e.target.value==='all'?null:e.target.value})}><option value="all">Все уровни риска</option><option value="low">Низкий риск</option><option value="medium">Средний риск</option><option value="high">Высокий риск</option></select></label></div>;}

export default function App() {
  const [query,setQuery]=useState(readQuery);
  const view=(['network','routes','incidents','history','settings'].includes(query.get('view')||'')?query.get('view'):'network') as View;
  const routeId=query.get('route'), tab=query.get('tab')||'overview';
  const period=[30,60,180].includes(Number(query.get('period')))?Number(query.get('period')):60;
  const direction=query.get('direction')==='1'?1:0;
  const riskFilter=(['low','medium','high'].includes(query.get('risk')||'')?query.get('risk'):'all') as Risk|'all';
  const search=query.get('q')||'';
  const serviceFilter=(['all','night','day'].includes(query.get('service')||'')?query.get('service'):'night') as ServiceFilter;
  const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[requesting,setRequesting]=useState(false);
  const [favorites,setFavorites]=useState<FavoriteRoute[]>(readFavorites);
  const [preview,setPreview]=useState<Route|null>(null);
  const previewPanel=useRef<HTMLElement>(null);
  const previewOpener=useRef<HTMLElement|null>(null);
  const favoriteIds=useMemo(()=>new Set(favorites.map(r=>r.id)),[favorites]);
  function showRouteDetails(r:Route){previewOpener.current=document.activeElement as HTMLElement;setPreview(r);}
  function closeRouteDetails(){setPreview(null);previewOpener.current?.focus();}
  useEffect(()=>{if(preview)previewPanel.current?.focus();},[preview?.id]);
  const [selected,setSelected]=useState<Vehicle|null>(null),[sort,setSort]=useState<'risk'|'number'>('risk');
  const [acknowledged,setAcknowledged]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('acknowledged-incidents')||'[]');}catch{return [];}});
  const [toast,setToast]=useState('');
  const drawer=useRef<HTMLDialogElement>(null);
  const loadedSlice=useRef('');
  function navigate(values:Record<string,string|null>){const q=readQuery();Object.entries(values).forEach(([k,v])=>v===null?q.delete(k):q.set(k,v));window.history.pushState({},'',`/?${q}`);setQuery(q);}
  useEffect(()=>{const listener=()=>setQuery(readQuery());window.addEventListener('popstate',listener);return()=>window.removeEventListener('popstate',listener);},[]);
  useEffect(()=>{setPreview(null);},[view,routeId]);
  const selectVehicle=useCallback((vehicle:Vehicle)=>{setSelected(vehicle);},[]);
  useEffect(()=>{if(selected && !drawer.current?.open) drawer.current?.showModal();},[selected]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{
    const sync=()=>{try{setFavorites(readFavorites());setAcknowledged(JSON.parse(localStorage.getItem('acknowledged-incidents')||'[]'));}catch{/* local preferences can be reset */}};
    window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);
  },[]);
  useEffect(()=>{
    const controller=new AbortController();let active=true;
    setLoading(true);setError('');
    const slice=`${routeId}:${direction}:${period}`;
    if(loadedSlice.current!==slice){setData(null);setSelected(null);loadedSlice.current=slice;}
    async function load(){setRequesting(true);try{const result=await api.snapshot(routeId,direction,period,controller.signal);if(active){setData(result);setError('');}}catch(e){if(active&&!controller.signal.aborted)setError((e as Error).message);}finally{if(active){setLoading(false);setRequesting(false);}}}
    void load();const timer=setInterval(()=>{if(!document.hidden)void load();},15000);
    const visible=()=>{if(!document.hidden)void load();};document.addEventListener('visibilitychange',visible);
    return()=>{active=false;controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',visible);};
  },[routeId,direction,period,refresh]);
  const route=data?.routes.find(r=>r.id===routeId);
  const filteredRoutes=useMemo(()=>{
    const term=search.trim().toLocaleLowerCase('ru');
    return (data?.routes||[]).filter(r=>(serviceFilter==='all'||r.serviceType===serviceFilter)&&(riskFilter==='all'||r.risk===riskFilter)&&(!term||`${r.number} ${r.name}`.toLocaleLowerCase('ru').includes(term))).sort((a,b)=>(view==='routes'?Number(favoriteIds.has(b.id))-Number(favoriteIds.has(a.id)):0)||(sort==='risk'?b.summary.worstDelaySeconds-a.summary.worstDelaySeconds:a.number.localeCompare(b.number,'ru',{numeric:true})));
  },[data,riskFilter,search,sort,view,favoriteIds,serviceFilter]);
  const serviceRoutes=(data?.routes||[]).filter(r=>serviceFilter==='all'||r.serviceType===serviceFilter);
  const serviceVehicles=serviceRoutes.flatMap(r=>r.vehicles);
  const serviceSummary:Summary={activeVehicles:serviceVehicles.length,routeCount:serviceRoutes.length,highRiskCount:serviceVehicles.filter(v=>v.risk==='high').length,incidentCount:serviceVehicles.filter(v=>v.risk!=='low').length,averageDelaySeconds:Math.round(serviceVehicles.reduce((sum,v)=>sum+v.delaySeconds,0)/Math.max(1,serviceVehicles.length)),worstDelaySeconds:Math.max(0,...serviceVehicles.map(v=>v.delaySeconds)),freshPercent:Math.round(100*serviceVehicles.filter(v=>v.ageSeconds<=data!.settings.staleAfterSeconds).length/Math.max(1,serviceVehicles.length))};
  const filteredIncidents=(data?.incidents||[]).filter(i=>(routeId||serviceFilter==='all'||serviceRoutes.some(r=>r.id===i.routeId))&&(riskFilter==='all'||i.risk===riskFilter)&&(!search||`${i.routeNumber} ${i.id} ${i.targetStop}`.toLocaleLowerCase('ru').includes(search.toLocaleLowerCase('ru'))));
  const heading=route?`Маршрут ${route.number}`:view==='network'?'Обзор сети':view==='settings'?'Настройки риска':names[view];
  useEffect(()=>{document.title=`${heading} — Диспетчерская`;},[heading]);
  function toggleFavorite(r:FavoriteRoute){const removing=favoriteIds.has(r.id);const next=removing?favorites.filter(f=>f.id!==r.id):[...favorites,{id:r.id,number:r.number}];setFavorites(next);try{localStorage.setItem(FAVORITES_KEY,JSON.stringify(next));localStorage.removeItem('pinned-route');}catch{setToast('Избранное сохранено только в этой вкладке');return;}setToast(removing?'Маршрут удалён из избранного':'Маршрут добавлен в избранное');}
  function FavoriteButton({route:r,compact=false}:{route:FavoriteRoute;compact?:boolean}){const active=favoriteIds.has(r.id);return <button type="button" className={`favorite-button ${compact?'compact':''} ${active?'is-favorite':''}`} aria-label={`${active?'Убрать маршрут':'Добавить маршрут'} ${r.number} ${active?'из избранного':'в избранное'}`} title={active?'Убрать из избранного':'Добавить в избранное'} aria-pressed={active} onClick={e=>{e.stopPropagation();toggleFavorite(r);}}><Star size={18} fill={active?'currentColor':'none'}/>{!compact&&(active?'В избранном':'В избранное')}</button>;}

  function acknowledge(v:Vehicle){const next=acknowledged.includes(v.id)?acknowledged.filter(id=>id!==v.id):[...acknowledged,v.id];setAcknowledged(next);try{localStorage.setItem('acknowledged-incidents',JSON.stringify(next));}catch{/* In-memory fallback */}}
  function RouteTable({routes}:{routes:Route[]}) {return <div className="table-scroll"><table><thead><tr><th><span className="sr-only">Избранное</span><Star size={15}/></th><th>№</th><th>Наименование</th><th>Тип</th><th><button className="table-sort" onClick={()=>setSort(sort==='risk'?'number':'risk')}>Статус <ArrowUpDown size={13}/></button></th><th>ТС в демо</th><th>Интервал</th><th>Наихудшая задержка</th><th><span className="sr-only">Подробнее</span></th></tr></thead><tbody>{routes.map(r=><tr key={r.id} data-route-id={r.id} className={`route-row ${favoriteIds.has(r.id)?'favorite-row':''}`} onClick={()=>showRouteDetails(r)}><td className="favorite-cell"><FavoriteButton route={r} compact/></td><td><button className="route-number" onClick={e=>{e.stopPropagation();showRouteDetails(r);}} title="Подробнее о маршруте">{r.number}</button></td><td><button className="route-link" onClick={e=>{e.stopPropagation();showRouteDetails(r);}}>{r.name}</button></td><td><span className="transport-type"><BusFront size={16}/>{r.transport}</span></td><td><RiskBadge risk={r.risk}/></td><td>{r.summary.activeVehicles}</td><td>{r.intervalMinutes} мин</td><td className={`delay-value ${r.risk}`}>{delay(r.summary.worstDelaySeconds)}</td><td><button className="text-button" aria-label={`Подробнее о маршруте ${r.number}`} onClick={e=>{e.stopPropagation();showRouteDetails(r);}}><ChevronRight size={16}/></button></td></tr>)}</tbody></table>{!routes.length&&<Empty>Маршруты не найдены</Empty>}</div>;}

  function Attention({all=false}:{all?:boolean}) {const items=filteredIncidents.slice(0,all?undefined:3);return <section className={`panel attention ${all?'all-incidents':''}`}><div className="section-heading"><h2>{route?'Инциденты маршрута':'Требуют внимания'} <span className="count-badge">{filteredIncidents.length}</span></h2>{!all&&<button className="text-button" onClick={()=>route?navigate({tab:'incidents'}):navigate({view:'incidents'})} aria-label="Все инциденты"><ArrowRight size={18}/></button>}</div><div className="incident-list">{items.map(v=><button key={v.id} className="incident" onClick={()=>selectVehicle(v)}><span className={`incident-icon ${v.risk}`}><TriangleAlert size={19}/></span><span className="incident-body"><span className="incident-top"><strong>{route?`ТС ${v.id}`:`Маршрут ${v.routeNumber}`}</strong>{!route&&<span>ТС {v.id}</span>}<ChevronRight size={15}/></span><span className="incident-prediction">Прогноз <b className={v.risk}>{delay(v.delaySeconds)}</b><span>Риск &gt;2 мин <b>{Math.round(v.probability*100)}%</b></span></span><span className="incident-detail">Сигнал: {v.signal.toLocaleLowerCase('ru')}</span><span className="incident-detail">К остановке: {v.targetStop}</span><span className="incident-footer"><span className={v.ageSeconds>(data?.settings.staleAfterSeconds||90)?'stale':''}>Данные: {age(v.ageSeconds)}</span>{acknowledged.includes(v.id)&&<span className="good"><Check size={12}/>Просмотрено</span>}</span></span></button>)}</div>{!items.length&&<Empty>Инцидентов не найдено</Empty>}</section>;}

  function History(){const events=(data?.historyEvents||[]).filter(e=>(riskFilter==='all'||e.risk===riskFilter)&&(!search||`${e.routeNumber} ${e.vehicleId}`.includes(search)));return <><section className="panel chart-panel"><div className="section-heading"><h2>Прогнозируемое отклонение {route?'на маршруте':'в сети'}</h2><span className="subtle">Демонстрационная история</span></div><Chart points={(data?.history||[]).map(p=>({label:time(p.time),a:p.maximum/60,b:p.average/60}))}/></section><section className="panel"><div className="section-heading"><h2>Журнал прогнозов</h2><button onClick={()=>downloadCsv([['Время','Маршрут','ТС','Задержка, сек'],...events.map(e=>[e.time,e.routeNumber,e.vehicleId,String(e.delaySeconds)])],'predictions-demo.csv')}><ArrowDownToLine size={16}/>Экспорт CSV</button></div><div className="table-scroll"><table><thead><tr><th>Время, МСК</th><th>Маршрут</th><th>ТС</th><th>Событие</th><th>Отклонение</th><th>Риск</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{time(e.time)}</td><td><button className="route-number" onClick={()=>{const r=data?.routes.find(r=>r.id===e.routeId);if(r)showRouteDetails(r);}}>{e.routeNumber}</button></td><td>{e.vehicleId}</td><td>{e.message}</td><td>{delay(e.delaySeconds)}</td><td><RiskBadge risk={e.risk}/></td></tr>)}</tbody></table>{!events.length&&<Empty>События не найдены</Empty>}</div></section></>;}
  return <div className="app-shell" style={data?{'--risk-low':data.settings.colors.low,'--risk-medium':data.settings.colors.medium,'--risk-high':data.settings.colors.high} as React.CSSProperties:undefined}>
    <a href="#main" className="skip-link">К содержимому</a>
    <aside className="sidebar"><a className="brand" href="/" aria-label="Диспетчерская — обзор сети"><BusFront size={33} strokeWidth={1.6}/><span>Диспетчерская</span></a><nav aria-label="Основная навигация">{(['network','routes','incidents','history'] as View[]).map(item=>{const Icon=icons[item];return <a key={item} href={`/?view=${item}`} className={(routeId?item==='routes':view===item)?'active':''} onClick={e=>{if(!e.ctrlKey&&!e.metaKey){e.preventDefault();navigate({view:item,route:null,tab:null,q:null,direction:null});}}}><Icon size={21} strokeWidth={1.6}/><span>{names[item]}</span></a>;})}</nav><div className="sidebar-bottom"><a href="/?view=settings" className={view==='settings'?'active':''} onClick={e=>{if(!e.ctrlKey&&!e.metaKey){e.preventDefault();navigate({view:'settings',route:null,tab:null});}}}><Settings2 size={20}/><span>Настройки</span></a><div className="operator"><span>Д</span><div>Диспетчер<small>Демо-доступ</small></div></div></div></aside>
    <main id="main">
      {routeId&&<div className="breadcrumbs"><a href="/">Сеть</a><ChevronRight size={13}/><a href="/?view=routes">Маршруты</a><ChevronRight size={13}/><span>{route?`Маршрут ${route.number}`:'Маршрут'}</span><a href="/" className="back-link"><ArrowLeft size={14}/>Обзор сети</a></div>}
      <header className="page-header"><div><div className="title-row"><h1>{heading}</h1>{route&&<span className="status-pill"><i/>Демо-линия</span>}</div>{route&&<p className="route-subtitle">{route.name}</p>}</div><div className="header-actions">{route?<><FavoriteButton route={route}/><label className="select-icon"><Clock3 size={16}/><select aria-label="Период" value={period} onChange={e=>navigate({period:e.target.value})}><option value={30}>Последние 30 минут</option><option value={60}>Последний час</option><option value={180}>Последние 3 часа</option></select></label></>:<div className="header-clock"><strong>{new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'})}</strong><span>Москва · МСК</span></div>}<button className="icon-button" aria-label="Обновить данные" title="Обновить данные" disabled={requesting} onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={17} className={requesting?'spin':''}/></button></div></header>
      <div className="mobile-shortcuts"><a href="/?view=settings" onClick={e=>{e.preventDefault();navigate({view:'settings',route:null,tab:null});}}><Settings2 size={14}/>Настройки</a></div>
      <div className="data-strip"><span><i className={`connection-dot ${error?'disconnected':''}`}/>{data?.mode==='live'?'Онлайн':'Демонстрационный режим'}</span><span>Реальные линии · тестовые ТС и прогнозы</span><span className="data-updated">Снимок {data?time(data.generatedAt):'—'} · автообновление 15 сек <Info size={13}/></span></div>
      {error&&<div className="error-banner" role="alert"><TriangleAlert size={18}/><div><strong>{data?'Нет связи с API. Показан последний полученный снимок.':'Не удалось загрузить данные'}</strong><span>{error}</span></div><button onClick={()=>setRefresh(v=>v+1)}>Повторить</button></div>}
      {loading&&!data?<div className="loading-state" role="status"><LoaderCircle className="spin" size={27}/><strong>Загружаем диспетчерскую…</strong></div>:data&&<>
        {routeId&&!route?<div className="empty-state">Маршрут не найден<a href="/?view=routes">Открыть каталог</a></div>:route?<>
          <div className="route-tabs" role="navigation" aria-label="Разделы маршрута">{[['overview','Обзор'],['whatif','What-if'],['incidents','Инциденты'],['history','История']].map(([value,label])=><button key={value} className={tab===value?'active':''} onClick={()=>navigate({tab:value})}>{label}</button>)}{tab==='whatif'&&<span className="model-note"><Info size={14}/>Модель сценариев · демо</span>}</div>
          {tab==='whatif'?<ScenarioView key={`${route.id}:${direction}`} route={route} settings={data.settings} onSelect={selectVehicle} direction={direction} onDirection={v=>navigate({direction:String(v)})}/>:tab==='history'?<History/>:tab==='incidents'?<><div className="list-toolbar"><h2>Прогнозы, требующие внимания</h2><Filters view={view} search={search} riskFilter={riskFilter} navigate={navigate}/></div><Attention all/></>:<>
            <Metrics summary={route.summary} routeMode/>
            <div className="route-direction"><label>Направление <select aria-label="Направление маршрута" value={direction} onChange={e=>navigate({direction:e.target.value})}><option value={0}>Прямое</option>{route.directionCount>1&&<option value={1}>Обратное</option>}</select></label><span>Остановки и участки риска — приближённая демонстрация</span></div>
            <div className="map-and-attention route-map-row"><Suspense fallback={<div className="map-panel skeleton"/>}><TransportMap routes={[route]} settings={data.settings} routeMode selected={selected} onSelect={selectVehicle}/></Suspense><Attention/></div>
            <div className="route-bottom"><section className="panel chart-panel"><div className="section-heading"><h2>Прогнозируемое отклонение на маршруте</h2><Info size={15} className="muted"/></div><Chart points={data.history.map(p=>({label:time(p.time),a:p.maximum/60,b:p.average/60}))}/><p className="chart-footnote">Демо-история · последние {period} минут</p></section><section className="panel stop-panel"><div className="section-heading"><h2>Остановки по маршруту</h2><span className="subtle">Приближённо</span></div><div className="table-scroll"><table className="stop-table"><thead><tr><th>Остановка</th><th>По плану</th><th>Прогноз</th><th>Отклонение</th></tr></thead><tbody>{route.stops.map(s=><tr key={s.id} className={s.delaySeconds===Math.max(...route.stops.map(x=>x.delaySeconds))?'worst-stop':''}><td><span className="stop-dot"/>{s.name}</td><td>{time(s.scheduledAt)}</td><td>{time(s.predictedAt)}</td><td className={s.risk}>{delay(s.delaySeconds)}</td></tr>)}</tbody></table></div></section></div>
          </>}
        </>:view==='settings'?<SettingsView settings={data.settings} onSaved={()=>{void api.snapshot(null,direction,period).then(setData).catch(e=>setError(e.message));}}/>:view==='history'?<><div className="list-toolbar"><h2>История сети</h2><Filters view={view} search={search} riskFilter={riskFilter} navigate={navigate}/></div><History/></>:view==='incidents'?<><Metrics summary={serviceSummary} routeMode={false}/><div className="list-toolbar"><h2>Инциденты сети <span className="subtle">{filteredIncidents.length}</span></h2><Filters view={view} search={search} riskFilter={riskFilter} navigate={navigate}/></div><Attention all/></>:<>
          <div className="service-filter" role="group" aria-label="Тип маршрутов">{([['night','Ночные маршруты'],['day','Дневные маршруты'],['all','Все']] as [ServiceFilter,string][]).map(([value,label])=><button key={value} className={serviceFilter===value?'active':''} aria-pressed={serviceFilter===value} onClick={()=>navigate({service:value==='night'?null:value})}>{label}<small>{value==='all'?data.routes.length:data.routes.filter(r=>r.serviceType===value).length}</small></button>)}</div>
          <Metrics summary={serviceSummary} routeMode={false}/>
          {view==='network'&&<div className="map-and-attention"><Suspense fallback={<div className="map-panel skeleton"/>}><TransportMap routes={filteredRoutes} settings={data.settings} selected={selected} onSelect={selectVehicle} onRouteSelect={id=>{const r=data.routes.find(r=>r.id===id);if(r)showRouteDetails(r);}}/></Suspense><Attention/></div>}
          <section className="panel route-table-panel"><div className="section-heading"><h2>Маршруты <span className="subtle">{filteredRoutes.length}</span>{view==='routes'&&favorites.length>0&&<span className="favorites-hint"><Star size={13}/>Избранные — в начале</span>}</h2><Filters view={view} search={search} riskFilter={riskFilter} navigate={navigate}/></div><RouteTable routes={view==='network'?filteredRoutes.slice(0,6):filteredRoutes}/>{view==='network'&&filteredRoutes.length>6&&<button className="table-footer-link" onClick={()=>navigate({view:'routes'})}>Все {filteredRoutes.length} маршрутов <ArrowRight size={15}/></button>}</section>
        </>}
        <footer className="page-footer"><span><ShieldAlert size={13}/>Демо: прогнозы не предназначены для оперативных решений</span><span>Геометрия: открытые данные Москвы · август 2026</span></footer>
      </>}
      {preview&&<aside ref={previewPanel} tabIndex={-1} className="vehicle-dialog route-preview" aria-label={`Подробности маршрута ${preview.number}`} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();closeRouteDetails();}}}>
        <div className="drawer-heading"><span className="drawer-bus"><BusFront size={26}/></span><div><h2>Маршрут {preview.number}</h2><span>{preview.transport}</span></div><button className="icon-button" aria-label="Закрыть подробности маршрута" onClick={closeRouteDetails}><X size={20}/></button></div>
        <p className="preview-route-name">{preview.name}</p><RiskBadge risk={preview.risk}/>
        <dl><div><dt>ТС на линии</dt><dd>{preview.summary.activeVehicles} в демо-сценарии</dd></div><div><dt>Инциденты</dt><dd>{preview.summary.incidentCount}</dd></div><div><dt>Среднее отклонение</dt><dd>{delay(preview.summary.averageDelaySeconds)}</dd></div><div><dt>Наихудшая задержка</dt><dd className={preview.risk}>{delay(preview.summary.worstDelaySeconds)}</dd></div><div><dt>Интервал движения</dt><dd>{preview.intervalMinutes} мин</dd></div><div><dt>Данные свежие</dt><dd>{preview.summary.freshPercent}%</dd></div></dl>
        <FavoriteButton route={preview}/><a className="primary-button preview-go" href={routeHref(preview.id)} target="_blank" rel="noreferrer">Перейти<ExternalLink size={16}/></a><p className="help-text">Страница маршрута откроется в новой вкладке. Показатели демонстрационные.</p>
      </aside>}
      <dialog ref={drawer} className="vehicle-dialog" onCancel={()=>setSelected(null)} onClose={()=>setSelected(null)}>{selected&&<><div className="drawer-heading"><span className="drawer-bus"><BusFront size={26}/></span><div><h2>ТС {selected.id}</h2><span>Маршрут {selected.routeNumber}</span></div><button className="icon-button" aria-label="Закрыть карточку ТС" onClick={()=>{drawer.current?.close();setSelected(null);}}><X size={20}/></button></div><RiskBadge risk={selected.risk}/><div className="vehicle-delay"><strong className={selected.risk}>{delay(selected.delaySeconds)}</strong><span>прогнозируемая задержка</span></div><dl><div><dt>Целевая остановка</dt><dd>{selected.targetStop}</dd></div><div><dt>Риск задержки &gt;2 мин</dt><dd>{Math.round(selected.probability*100)}% <small>демо-вероятность</small></dd></div><div><dt>Наблюдаемый сигнал</dt><dd>{selected.signal}</dd></div><div><dt>Скорость</dt><dd>{selected.speedKmh} км/ч</dd></div><div><dt>Последний пакет</dt><dd>{time(selected.observedAt)} МСК · {age(selected.ageSeconds)}</dd></div></dl><p className="help-text">Сигнал описывает наблюдение, а не подтверждённую причину задержки. Данные ТС демонстрационные.</p><button className={`acknowledge-button ${acknowledged.includes(selected.id)?'is-acknowledged':''}`} aria-pressed={acknowledged.includes(selected.id)} onClick={()=>acknowledge(selected)}><span className="acknowledge-checkbox"><Check size={18}/></span>{acknowledged.includes(selected.id)?'Снять отметку просмотра':'Отметить просмотренным'}</button><p className="help-text acknowledgement-note">Отметка «просмотрено» сохраняется в этом браузере и доступна при следующем визите.</p><a className="drawer-route-link" href={routeHref(selected.routeId)} target="_blank" rel="noreferrer">Открыть маршрут в новой вкладке<ExternalLink size={15}/></a></>}</dialog>
      {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
    </main>
  </div>;
}
